Add storage implementation wrapping ZipArchive
Arlodotexe/OwlCore.Storage pull request #10
Opened 2023-01-11 08:56 UTC by yoshiask

# Overview
This PR adds `IFolder` and `IFile` implementations for wrapping `ZipArchive` and `ZipArchiveEntryFile`, respectively.

Some oddities arise with this implementation, due to the nature of ZIP files:

1. ZIP files don't really have directories, at least not when loaded by .NET's `ZipArchive`. This means that a subfolder doesn't really exist until the consumer calls `CreateFolderAsync`, even if a file already exists inside it. For example, a file exists at `archiveRoot\sub\file.txt`. A call to `GetItemsAsync` will only return the file, unless the consumer explicitly called `CreateFolderAsync(sub)` before.
2. In addition to the above, some programs that create ZIP files (for example, the "Send to" option in Windows Explorer) will create explicit entries for directories. This implementation could do the same when creating directories, but it cannot be relied on for reading existing archives since some programs (for example, WinZip) do not do this.
3. `ZipArchiveFolder` is a folder implementation that actually wraps a file, or more accurately a stream. As such, there is no practical way to implement a file watcher. This is further complicated by the fact that the wrapped stream might be changed outside of the `ZipArchiveFolder`'s control, but I consider this to be an unsupported scenario.
4. `ZipArchiveEntryFile.OpenStreamAsync` can't respect the `accessMode` parameter, since the access mode of the entry is dependent on the access mode of the `ZipArchive` it resides in.

2023-01-11 09:02 UTC, yoshiask commented
Howdy! I have opened this PR as a draft since I'm almost certain that my current implementation doesn't work properly with subfolders.

2023-01-11 19:31 UTC, Arlodotexe commented
Thanks for the PR! Excited to see the end result. When you've done all you can, we'll begin review on this and get it polished up for release.

2023-01-12 16:09 UTC, Arlodotexe commented on src/SystemIO/Compression/ZipArchiveEntryFile.cs
> +namespace OwlCore.Storage.SystemIO.Compression;
A couple of suggestions for the namespace and class naming. These new classes are located in a subfolder of SystemIO, making the fullname `OwlCore.Storage.SystemIO.Compression.ZipArchiveFolder`. I think it would be more appropriate to move these classes to `OwlCore.Storage.Archive`, and remove `Archive` from the name of the classes. This aligns with the conventions used in the MemoryFolder class, which specifies where data is being handled, rather than the underlying implementation used to interact with it. It's also much easier to remember and will allow a single `using` to import types for other archive formats in the future.

2023-01-12 16:13 UTC, yoshiask commented on src/SystemIO/Compression/ZipArchiveEntryFile.cs
> +namespace OwlCore.Storage.SystemIO.Compression;
This was one of the things I wasn't sure about, but decided to go with the convention used for SystemFolder/File since their underlying implementations are in the same place (that is, `System.IO`). I'll make the change.

2023-01-13 15:39 UTC, Arlodotexe requested changes

2023-01-13 15:39 UTC, Arlodotexe commented on tests/OwlCore.Storage.Tests/Archive/Zip/InMemIFolderTests.cs
> +namespace OwlCore.Storage.Tests.Archive.Compression;
Namespace does not match folder path

2023-01-13 15:39 UTC, Arlodotexe commented on tests/OwlCore.Storage.Tests/Archive/Zip/IFolderTests.cs
> +namespace OwlCore.Storage.Tests.Archive.Compression;
Namespace does not match folder path

2023-01-13 15:39 UTC, Arlodotexe commented on src/Archive/ZipFolder.cs
> +    public ZipFolder(string id, string name, ZipArchive archive, string path = "")
Can you provide details on why you chose these constructor parameters? If it doesn't conflict, I'd like to swap all of these out with a single `IFile` parameter that represents the zip file being read as a folder.

2023-01-13 15:39 UTC, Arlodotexe commented on src/Archive/ZipFolder.cs
> +        else if (srcStream.Position == 0)
```suggestion
        else if (srcStream.Position != 0)
```

2023-01-13 15:39 UTC, Arlodotexe commented on src/Archive/ZipFolder.cs
> +            // NOTE: Should this be recursive, or should it
This should be recursive. In every file system I can think of, if you delete a folder, all contents in that folder are also deleted, so that's the behavior we use here.

2023-01-13 15:39 UTC, Arlodotexe commented on tests/OwlCore.Storage.Tests/Archive/Zip/IFolderTests.cs
> +        ZipArchive archive = ZipFile.Open(CreateEmptyArchiveOnDisk(), ZipArchiveMode.Update);
Since our implementation decides whether the folder is modifiable, we should have separate implementations for Read mode and Update mode, rather than letting the user decide the update mode then have our implementation assume it's always modifiable.

From the docs:
> When you set the mode to Read, the underlying file or stream must support reading, but does not have to support seeking. If the underlying file or stream supports seeking, the files are read from the archive as they are requested. If the underlying file or stream does not support seeking, the entire archive is held in memory.

> When you set the mode to Update, the underlying file or stream must support reading, writing, and seeking. The content of the entire archive is held in memory, and no data is written to the underlying file or stream until the archive is disposed.

When `Update` is used, or when arbitrary content is requested to be read, the entire underlying stream is loaded into memory. Let's create a `ReadOnlyZipFolder` that can be used to avoid reading the whole thing into memory. Since `GetItemsAsync` returns `IAsyncEnumerable`, the underlying stream will only advance as the content is read and no sooner.

This makes it conceivably possible to pass an `HttpFile` in as a Zip file and still let you read it (HTTP response streams don't usually seek).

Would end up looking like this after all suggestions are applied:

```cs
public class ReadOnlyZipFolder : IFolder
{
    public ReadOnlyZipFolder(IFile zipFile)
    {
        ...
    }
    
    public async Task AnyMethodAsync(CancellationToken token)
    {
        // Open the stream and create read-only ZipArchive
        using var stream = await _zipFile.OpenStreamAsync();
        var archive = new ZipArchive(archiveStream, ZipArchiveMode.Read);
        // Do something with archive.
    }
}

public class ZipFolder : IModifiableFolder, ReadOnlyZipFolder
{
    public ZipFolder(IFile zipFile) : base(zipFile)
    {
        ...
    }
    
    public async Task AnyMethodAsync(CancellationToken token)
    {
        // Open the stream and create updatable ZipArchive
        using var stream = await _zipFile.OpenStreamAsync();
        var archive = new ZipArchive(archiveStream, ZipArchiveMode.Update);
        // Do something with archive.
    }
}
```

2023-01-13 15:44 UTC, Arlodotexe commented on tests/OwlCore.Storage.Tests/Archive/Zip/IFolderTests.cs
> +        ZipArchive archive = ZipFile.Open(CreateEmptyArchiveOnDisk(), ZipArchiveMode.Update);
I could forsee this causing deadlocks when run concurrently, which should break tests. If that happens, just wrap file access in a semaphore.

2023-01-13 15:46 UTC, yoshiask commented on src/Archive/ZipFolder.cs
> +            // NOTE: Should this be recursive, or should it
I replicated the behavior from `SystemFolder`, where [`Directory.Delete(string)`](https://learn.microsoft.com/en-us/dotnet/api/system.io.directory.delete?view=net-7.0#system-io-directory-delete(system-string-system-boolean)) is called.

2023-01-13 15:52 UTC, Arlodotexe commented on src/Archive/ZipFolder.cs
> +            // NOTE: Should this be recursive, or should it
Looks like a bug in SystemFolder. We'll fix that, thanks!

2023-01-13 15:56 UTC, yoshiask commented on src/Archive/ZipFolder.cs
> +    public ZipFolder(string id, string name, ZipArchive archive, string path = "")
Sure. I avoided taking an `IFile` because it meant calling `OpenStreamAsync` within the folder implementation just to get the `ZipArchive`. This prevents initialization from being done in the constructor and, more importantly, would require `ZipFolder` to decide when to close the stream.

2023-01-17 20:09 UTC, Arlodotexe commented on tests/OwlCore.Storage.Tests/Archive/Zip/IFolderTests.cs
> +        ZipArchive archive = ZipFile.Open(CreateEmptyArchiveOnDisk(), ZipArchiveMode.Update);
From our conversation on Discord, let's instead pass a raw stream + an instance of IStorable into the constructor.

2023-01-17 20:11 UTC, Arlodotexe commented on src/Archive/ZipFolder.cs
> +    public ZipFolder(string id, string name, ZipArchive archive, string path = "")
Resolving for now, see remaining comment:  https://github.com/Arlodotexe/OwlCore.Storage/pull/10#discussion_r1069596347

2023-01-31 00:59 UTC, Arlodotexe approved these changes

2023-01-31 02:48 UTC, merged