v0.8.0: Move/Copy improvements, removed path, improved names, new interfaces / extension methods
Arlodotexe/OwlCore.Storage pull request #19
Opened 2023-02-18 22:22 UTC by Arlodotexe

### Summary
- Closes #18
- Closes #17 
- Closes #9 
- Renames several interfaces using feedback from @yoshiask and d2d1 from the UWP Community.
- Adds several new extension methods to cover

2023-02-19 00:11 UTC, Arlodotexe commented on src/Extensions/CopyAndMoveExtensions.cs
> +    /// Moves a storable item out of the provided folder, and into this folder. Returns the new item that resides in this folder.
```suggestion
    /// Moves a storable item out of the source folder, and into the destination folder. Returns the new item that resides in this folder.
```

2023-02-19 00:11 UTC, Arlodotexe commented on src/Extensions/GetItemByRelativePathExtension.cs
> +    /// Or, the provided relative path named a folder, but the item was a file.
```suggestion
    /// Or, the provided relative path named a folder, but the item was a file.
    /// Or, an empty path part was found.
```

2023-02-19 00:11 UTC, Arlodotexe commented on src/Extensions/GetItemByRelativePathExtension.cs
> +    /// Traverses the relative path from the provided <see cref="IStorable"/> and returns the item at that path.
```suggestion
    /// From the provided <see cref="IStorable"/>, traverses the provided relative path and returns the item at that path.
```

2023-02-19 00:11 UTC, Arlodotexe commented on src/Extensions/GetItemRecursiveExtension.cs
> +                throw new ArgumentException(@$"The item returned by the interface ""{nameof(IFastGetItemRecursive)}"" implemented in ""{folder.GetType()}"" does not have the expected Id ""{id}"". Act
```suggestion
                throw new ArgumentException(@$"The item returned by the interface ""{nameof(IFastGetItemRecursive)}"" implemented in ""{folder.GetType()}"" does not have the requested Id ""{id}"". Actual value: ""{item.Id}"".", nameof(item));
```

2023-02-19 00:11 UTC, Arlodotexe commented on src/Extensions/GetItemRecursiveExtension.cs
> +            // Check the item is in this directory (supports all available fast paths)
```suggestion
            // Check that the item is in this directory (supports all available fast paths)
```

2023-02-19 00:11 UTC, Arlodotexe commented on src/Extensions/GetRelativePathToExtension.cs
> +    /// <remarks>Example code. Not tested.</remarks>
```suggestion
```

2023-02-19 00:11 UTC, Arlodotexe commented on src/Extensions/GetRootExtension.cs
> +    /// <returns></returns>
```suggestion
    /// <returns>The folder that this implementation considers the "root".</returns>
```

2023-02-19 00:11 UTC, Arlodotexe commented on src/Extensions/GetRootExtension.cs
> +    /// <param name="item">The item to which the root should be retrieved from.</param>
```suggestion
    /// <param name="item">The item which the root should be retrieved from.</param>
```

2023-02-19 00:11 UTC, Arlodotexe commented on src/IStorageProperty.cs
> +/// A property that was retrieved asynchronously, and can be disposed. The <paramref see="Value"/> can be a primitive or an object containing multiple values.
```suggestion
/// A property that was retrieved asynchronously, and can be disposed. The <see cref="Value"/> can be a primitive or an object containing multiple values.
```

2023-02-19 00:11 UTC, Arlodotexe commented on src/IStorageProperty.cs
> +/// The recommended pattern for properties is create an async method that returns <c>IStorageProperty{SomePropertyType}</c>, put that method on an interface, and use the interface to indicate support
```suggestion
/// The recommended pattern for properties is create an async method that returns <c>IStorageProperty{SomePropertyType}</c>, put that method on an interface, and use the interface to indicate optional support for this property value.
```

2023-02-19 15:33 UTC, amaid requested changes

2023-02-19 15:33 UTC, amaid commented on src/Archive/ReadOnlyZipArchiveFolder.cs
> +public class ReadOnlyZipArchiveFolder : IChildFolder, IFastGetRoot, IFastGetItem, IFastGetFirstByName, IDisposable
Looks like the names of the interfaces are verbs, ideally they should be nouns

2023-02-19 15:33 UTC, amaid commented on src/Archive/ReadOnlyZipArchiveFolder.cs
> +        cancellationToken.ThrowIfCancellationRequested();
Why not safely return if the TaskCancellation is requested using the `IsCancellationRequested` flag?

2023-02-19 15:33 UTC, amaid commented on src/Archive/ZipArchiveFolder.cs
>              entry?.Delete();
No async overload available for deletion?

2023-02-19 15:33 UTC, amaid commented on src/Archive/ZipArchiveFolder.cs
> +        throw new FileNotFoundException("The item was not found in the folder.");
Are you throwing unconditionally?

2023-02-19 15:33 UTC, amaid commented on src/Extensions/CopyAndMoveExtensions.cs
> +        if (destinationFolder is IFastFileCopy<T> fastPath)
How can a folder also be a FastFile? 
`// If the destination folder can copy this file faster than us, use that.`
What does copy faster means here?

2023-02-19 15:33 UTC, amaid commented on src/Extensions/CopyAndMoveExtensions.cs
> +        await sourceStream.CopyToAsync(destinationStream, bufferSize: 81920, cancellationToken);
No exception handling here? What if copy failed due to some reason?

2023-02-19 15:33 UTC, amaid commented on src/Extensions/CopyAndMoveExtensions.cs
> +        await source.DeleteAsync(fileToMove, cancellationToken);
No exception handling?

2023-02-19 15:33 UTC, amaid commented on src/Extensions/GetFilesAndFoldersExtensions.cs
> +    public static IAsyncEnumerable<IChildFile> GetFilesAsync(this IFolder folder, CancellationToken cancellationToken = default) => folder.GetItemsAsync(StorableType.File, cancellationToken).Cast<ICh
Maybe if the Items count is 0 don't cast it?

2023-02-19 15:33 UTC, amaid commented on src/Extensions/GetFilesAndFoldersExtensions.cs
> +    public static IAsyncEnumerable<IChildFolder> GetFoldersAsync(this IFolder folder, CancellationToken cancellationToken = default) => folder.GetItemsAsync(StorableType.Folder, cancellationToken).Ca
Maybe if the Items count is 0 don't cast it?

2023-02-19 15:33 UTC, amaid commented on src/Extensions/GetFirstByNameExtension.cs
> +    public static async Task<IStorableChild> GetFirstByNameAsync(this IFolder folder, string name, CancellationToken cancellationToken = default)
Maybe rename it to GetFirst`Item`ByName?

2023-02-19 15:33 UTC, amaid commented on src/Extensions/GetItemByRelativePathExtension.cs
> +    public static async Task<IStorable> GetItemByRelativePathAsync(this IStorable from, string relativePath, CancellationToken cancellationToken = default)
Nice one!!

2023-02-19 15:33 UTC, amaid commented on src/Extensions/GetRelativePathToExtension.cs
> +        return to switch
"Return to switch" that's new?

2023-02-19 15:33 UTC, amaid commented on src/HttpFile.cs
> +        MessageHandler = new HttpClientHandler();
This violates Inversion of Control, creation of an instance silently comes under hidden functionality, maybe pass the messageHandler from the constructor?

2023-02-19 15:33 UTC, amaid commented on src/Memory/MemoryFolder.cs
> +        var emptyMemoryFolder = new MemoryFolder($"{Guid.NewGuid()}", name)
Why MemoryFolder isn't disposable?

2023-02-19 15:33 UTC, amaid commented on src/SystemIO/SystemFolder.cs
> +        if (!Directory.Exists(Path))
Disk operation in a constructor? Isn't it a bit heavy lifting?

2023-02-19 15:33 UTC, amaid commented on src/SystemIO/SystemFolder.cs
> +            throw new FileNotFoundException($"Directory not found at path {Path}");
Maybe don't throw exception on instance creation?

2023-02-19 15:33 UTC, amaid commented on src/SystemIO/SystemFolder.cs
> +        Name = System.IO.Path.GetFileName(Path) ?? throw new ArgumentException($"Could not determine directory name from path {Path}");
Maybe don't throw exception on instance creation?

2023-02-19 15:33 UTC, amaid commented on src/SystemIO/SystemFolder.cs
> +            throw new FileNotFoundException($"The provided ID does not belong to an item in this folder.");
Are there any "Storage" related Ids that don't have paths appended? If no maybe just throw "Provided Id is invalid"?

2023-02-19 15:33 UTC, amaid commented on src/SystemIO/SystemFolder.cs
> +            File.Delete(item.Id);
No Async overload available?

2023-02-19 15:33 UTC, amaid commented on src/SystemIO/SystemFolder.cs
> +        File.Copy(fileToCopy.Path, newPath, overwrite);
No exception handling/throwing here?

2023-02-19 15:33 UTC, amaid commented on src/SystemIO/SystemFolder.cs
> +        File.Move(fileToMove.Path, newPath);
No exception handling/throwing here?

2023-02-19 16:01 UTC, Arlodotexe commented on src/Archive/ReadOnlyZipArchiveFolder.cs
> +public class ReadOnlyZipArchiveFolder : IChildFolder, IFastGetRoot, IFastGetItem, IFastGetFirstByName, IDisposable
From the [dotnet standard naming guidelines](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces):
> ✔️ DO name classes and structs with nouns or noun phrases, using PascalCasing.
> 
> This distinguishes type names from methods, which are named with verb phrases.
> 
> ✔️ DO name interfaces with adjective phrases, or occasionally with nouns or noun phrases.
> 
> Nouns and noun phrases should be used rarely and they might indicate that the type should be an abstract class, and not an interface.

2023-02-19 16:12 UTC, Arlodotexe commented on src/Archive/ReadOnlyZipArchiveFolder.cs
> +        cancellationToken.ThrowIfCancellationRequested();
Because task cancellation isn't designed to work like that. When cancellation happens, it's handled by catching a `OperationCanceledException`. That way, every method in the call stack has the ability to add more long-running requests, and it can be canceled by anyone in the call stack, at any stage. 

In a language like C#, "safe returns" (such as a nullable value), should only be used if it's part of the contract, and it's extremely clear what the value means. Maybe there'd be a case for a nullable return value instead of throwing `FileNotFoundException`, but not for task cancellation.

See [Task Cancellation @ Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/standard/parallel-programming/task-cancellation) for official recommendations, and [this guide from dotnettutorials](https://dotnettutorials.net/lesson/how-to-cancel-a-task-in-csharp/) for a decent breakdown of how it works.

2023-02-19 16:14 UTC, Arlodotexe commented on src/Archive/ZipArchiveFolder.cs
>              entry?.Delete();
That wasn't the point of this PR, but that's a good question. Mind checking? Can open a new ticket for later, if so.

2023-02-19 16:20 UTC, Arlodotexe commented on src/Archive/ZipArchiveFolder.cs
> +        throw new FileNotFoundException("The item was not found in the folder.");
Good catch! Fixed 🙂

2023-02-19 16:22 UTC, Arlodotexe commented on src/Extensions/CopyAndMoveExtensions.cs
> +        if (destinationFolder is IFastFileCopy<T> fastPath)
`IFastFileCopy<T>` means it can do a fast file copy for the provided type. Faster than we can do, manually.

2023-02-19 16:23 UTC, Arlodotexe commented on src/Extensions/CopyAndMoveExtensions.cs
> +        await sourceStream.CopyToAsync(destinationStream, bufferSize: 81920, cancellationToken);
See above comments about exception handling

2023-02-19 16:24 UTC, Arlodotexe commented on src/Extensions/CopyAndMoveExtensions.cs
> +        await source.DeleteAsync(fileToMove, cancellationToken);
See above comments about exception handling. It's the same reason task cancellation works so well via throwing.

2023-02-19 16:25 UTC, Arlodotexe commented on src/Extensions/GetFilesAndFoldersExtensions.cs
> +    public static IAsyncEnumerable<IChildFile> GetFilesAsync(this IFolder folder, CancellationToken cancellationToken = default) => folder.GetItemsAsync(StorableType.File, cancellationToken).Cast<ICh
I'm not sure why you would want to do this. Can you explain more?

2023-02-19 16:25 UTC, Arlodotexe commented on src/Extensions/GetFilesAndFoldersExtensions.cs
> +    public static IAsyncEnumerable<IChildFolder> GetFoldersAsync(this IFolder folder, CancellationToken cancellationToken = default) => folder.GetItemsAsync(StorableType.Folder, cancellationToken).Ca
If there are no items then t

2023-02-19 16:27 UTC, Arlodotexe commented on src/Extensions/GetFirstByNameExtension.cs
> +    public static async Task<IStorableChild> GetFirstByNameAsync(this IFolder folder, string name, CancellationToken cancellationToken = default)
Had that and it was too long. This is much shorter, especially noticeable on the interfaces. (Using `IFastGetFirstByName` instead of `IFastGetFirstItemByName`). I think it still gets the point across.

@yoshiask What are your thoughts here?

2023-02-19 16:28 UTC, Arlodotexe commented on src/Extensions/GetItemByRelativePathExtension.cs
> +    public static async Task<IStorable> GetItemByRelativePathAsync(this IStorable from, string relativePath, CancellationToken cancellationToken = default)
This one donated from Strix Music 😎
Glad you like it!

2023-02-19 16:33 UTC, Arlodotexe commented on src/Extensions/GetRelativePathToExtension.cs
> +        return to switch
`to` and `from` aren't reserved keywords, though `from` is a contextual keyword. It means we can use them as variable names in C#.

2023-02-19 16:33 UTC, Arlodotexe commented on src/HttpFile.cs
> +        MessageHandler = new HttpClientHandler();
It's completely normal to be instantiating things in the constructor. How else would you set up a class for use? 🙂

The MessageHandler here is the default, because it's required for our class to function. It can be overridden like any other property.

2023-02-19 16:42 UTC, Arlodotexe commented on src/Memory/MemoryFolder.cs
> +        var emptyMemoryFolder = new MemoryFolder($"{Guid.NewGuid()}", name)
MemoryFolder isn't holding any memory that need to be disposed.

It does contain a reference to a `MemoryFolderWatcher`, but disposing that class doesn't do anything. It will get cleaned up normally by the GC, so the consumer doesn't need to dispose it manually.

2023-02-19 16:48 UTC, Arlodotexe commented on src/SystemIO/SystemFolder.cs
> +        if (!Directory.Exists(Path))
For cases like this - where you take a random data and assume it's a working file - it's _highly_ recommended to do a synchronous check like this (if you can) to make sure it actually exists before working with it.

That goes for all implementations of OwlCore.Storage. If it's not possible or the call is too heavy, don't do it. Otherwise, _do it_.

Object instances like this can be passed around for quite a while before any problems start manifesting if you gave it a bad path, and it makes debugging problems with _your_ code that much harder.

2023-02-19 16:49 UTC, Arlodotexe commented on src/SystemIO/SystemFolder.cs
> +            throw new FileNotFoundException($"Directory not found at path {Path}");
Constructors are just fancy synchronous method calls, there's nothing wrong with throwing in the constructor if some bad data was provided and can't be used.

See above comment(s).

2023-02-19 16:50 UTC, Arlodotexe commented on src/SystemIO/SystemFolder.cs
> +        Name = System.IO.Path.GetFileName(Path) ?? throw new ArgumentException($"Could not determine directory name from path {Path}");
Constructors are just fancy synchronous method calls, there's nothing wrong with throwing in the constructor if some bad data was provided and can't be used.

See above comment(s).

2023-02-19 16:51 UTC, Arlodotexe commented on src/SystemIO/SystemFolder.cs
> +            throw new FileNotFoundException($"The provided ID does not belong to an item in this folder.");
It's expected that the provided ID is an ancestor of the current folder, and can always be found if you crawl the object graph for it. The phrasing here reflects that.

2023-02-19 16:52 UTC, Arlodotexe commented on src/SystemIO/SystemFolder.cs
> +            File.Delete(item.Id);
Not for System.IO, see [here](https://stackoverflow.com/questions/29013958/how-to-implement-an-async-file-delete-create-move).

2023-02-19 16:53 UTC, Arlodotexe commented on src/SystemIO/SystemFolder.cs
> +        File.Copy(fileToCopy.Path, newPath, overwrite);
There's no need to catch and rethrow the exception here. It can be done by the consumer if that's what they want.

2023-02-19 16:53 UTC, Arlodotexe commented on src/SystemIO/SystemFolder.cs
> +        File.Move(fileToMove.Path, newPath);
There's no need to catch and rethrow the exception here. It can be done by the consumer if that's what they want.

2023-02-19 16:57 UTC, Arlodotexe commented on src/HttpFile.cs
> +        MessageHandler = new HttpClientHandler();
🙂 It's completely normal to be instantiating things in the constructor. How else could you set up a class for use without overloading the consumer?

The MessageHandler here has a default value of `HttpClientHandler`, because it's required for our class to function. It can be reassigned by the consumer like any other property.

That said, I reviewed the file again and it looks like I didn't add the setter for the property. You found some unfinished changes. I've added an init-only setter, and moved the default value to the property itself, instead of the constructor.

2023-02-19 17:18 UTC, amaid commented on src/Archive/ReadOnlyZipArchiveFolder.cs
> +        cancellationToken.ThrowIfCancellationRequested();
Understood.

2023-02-19 17:22 UTC, amaid commented on src/Extensions/GetFilesAndFoldersExtensions.cs
> +    public static IAsyncEnumerable<IChildFile> GetFilesAsync(this IFolder folder, CancellationToken cancellationToken = default) => folder.GetItemsAsync(StorableType.File, cancellationToken).Cast<ICh
Something like:
`
var result = folder.GetItemsAsync(StorableType.File, cancellationToken);
if(!result.Any()){
 // return default or empty list of IChildFile instead of casting that can be expensive
}
return folder.GetItemsAsync(StorableType.File, cancellationToken).Cast<IChildFile>();;
`

2023-02-19 17:23 UTC, amaid commented on src/Extensions/GetFilesAndFoldersExtensions.cs
> +    public static IAsyncEnumerable<IChildFolder> GetFoldersAsync(this IFolder folder, CancellationToken cancellationToken = default) => folder.GetItemsAsync(StorableType.Folder, cancellationToken).Ca
Something like:
```csharp
var result = await folder.GetItemsAsync(StorableType.File, cancellationToken);
if(!result.Any()){
 // return default or empty list of IChildFile instead of casting that can be expensive
}
return folder.GetItemsAsync(StorableType.File, cancellationToken).Cast<IChildFile>();

2023-02-19 17:25 UTC, amaid commented on src/Memory/MemoryFolder.cs
> +        var emptyMemoryFolder = new MemoryFolder($"{Guid.NewGuid()}", name)
Makes sense.

2023-02-19 17:31 UTC, amaid commented on src/SystemIO/SystemFolder.cs
> +        File.Copy(fileToCopy.Path, newPath, overwrite);
Ahh this makes sense

2023-02-19 17:31 UTC, amaid commented on src/SystemIO/SystemFolder.cs
> +        File.Move(fileToMove.Path, newPath);
Ahh this makes sense

2023-02-19 17:38 UTC, amaid approved these changes

2023-02-19 17:57 UTC, Arlodotexe commented on src/Extensions/GetFilesAndFoldersExtensions.cs
> +    public static IAsyncEnumerable<IChildFile> GetFilesAsync(this IFolder folder, CancellationToken cancellationToken = default) => folder.GetItemsAsync(StorableType.File, cancellationToken).Cast<ICh
This adds complexity, creates a new async state machine that isn't needed, and doesn't change the behavior. Changing the number of items doesn't change the performance, because it's just a type cast. It would need to be _enumerated_ for the number of items to have an effect on performance, which we aren't doing here.

The call to `.Cast<T>` is negligible, we're going to keep it as-is.

2023-02-19 17:58 UTC, Arlodotexe commented on src/Extensions/GetFilesAndFoldersExtensions.cs
> +    public static IAsyncEnumerable<IChildFolder> GetFoldersAsync(this IFolder folder, CancellationToken cancellationToken = default) => folder.GetItemsAsync(StorableType.Folder, cancellationToken).Ca
See other thread - https://github.com/Arlodotexe/OwlCore.Storage/pull/19#discussion_r1111293865

2023-02-20 02:50 UTC, yoshiask commented on src/Archive/ZipArchiveFolder.cs
>              entry?.Delete();
No, `ZipArchive` does not have any asynchronous methods.

2023-02-20 02:52 UTC, yoshiask commented on src/Extensions/GetFirstByNameExtension.cs
> +    public static async Task<IStorableChild> GetFirstByNameAsync(this IFolder folder, string name, CancellationToken cancellationToken = default)
I agree that `GetFirstItemByName` is technically more descriptive, I also agree the interface name is already descriptive and long enough. On the off chance that someone doesn't know or isn't sure what the extension does just from the name, they can just read the XML doc summary.

2023-02-22 15:00 UTC, merged