Release 0.9.3 (general cleanup)
Arlodotexe/OwlCore.Storage pull request #47
Opened 2023-12-18 05:18 UTC by Arlodotexe

This PR:
- Bumps to version 0.9.3
- Underlying DirectoryInfo for SystemFile is now lazily loaded when using the path constructor and is now exposed via `SystemFile.Info`.
- Closes #43
- Closes #44
- Closes #45

2023-12-19 22:45 UTC, d2dyno1 requested changes

2023-12-19 22:45 UTC, d2dyno1 commented on src/IMutableFolder.cs
> +    /// <returns>A disposable object which can notify of changes to the folder.</returns>
`A <see cref="Task"/> that represents the asynchronous operation. Value is an <see cref="IFolderWatcher"/> object which can notify of changes to the folder.`

2023-12-19 22:45 UTC, d2dyno1 commented on src/IStorable.cs
> +/// The minimum representation of an item that can be stored or retrieved from storage.
"Represents a generic item that can be stored or retrieved from a storage source."

2023-12-19 22:45 UTC, d2dyno1 commented on src/IStorable.cs
> +    /// A unique and consistent identifier for this file or folder. This dedicated resource identifier is used to identify the exact file or folder you're pointing to.
Use the term "item" instead of specifically pointing to a concrete description of a folder/file when annotating properties within the base (IStorable) object

2023-12-19 22:45 UTC, d2dyno1 commented on src/IStorable.cs
>      /// </remarks>
"The core mechanism can utilize any string data available to create this ID, as long as it reliably and uniquely identifies this specific resource."

2023-12-19 22:45 UTC, d2dyno1 commented on src/IStorable.cs
>      /// The name of the file or folder, with the extension (if any).
Personally, I'd start the comment with "Gets... (e.g. a value indicating)" or use "Gets or sets... (e.g. a value indicating)" when a property has `{ get; set; }` accessors

2023-12-19 22:45 UTC, d2dyno1 commented on src/IStorableChild.cs
> +    /// <returns>The containing parent folder, if any.</returns>
First describe the Task as the return value and then the value itself within the Task (like above)

2023-12-19 22:45 UTC, d2dyno1 commented on src/SystemIO/SystemFile.cs
> +    /// The underlying <see cref="FileInfo"/> for this folder.
Same as above (and other places too)

2023-12-26 00:13 UTC, Arlodotexe commented on src/IStorable.cs
>      /// </remarks>
I'll merge yours with mine, and simplify it a bit.

2023-12-26 00:14 UTC, Arlodotexe commented on src/IStorable.cs
>      /// The name of the file or folder, with the extension (if any).
This is something I need to do a sweep of the entire codebase for, I'll save this for a different cleanup pass but file a ticket so we don't forget.

2023-12-26 00:16 UTC, Arlodotexe commented on src/IStorableChild.cs
> +    /// <returns>The containing parent folder, if any.</returns>
I purposely avoid this because docfx doesn't resolve system references and it produces broken links when you add docs.

2023-12-26 00:19 UTC, Arlodotexe commented on src/IStorable.cs
> +/// The minimum representation of an item that can be stored or retrieved from storage.
Avoiding the word 'generic' here, otherwise this is good.

2023-12-26 00:20 UTC, Arlodotexe commented on src/IStorable.cs
> +    /// A unique and consistent identifier for this file or folder. This dedicated resource identifier is used to identify the exact file or folder you're pointing to.
Good idea, that's cleaner.

2023-12-26 00:33 UTC, Arlodotexe commented on src/IStorable.cs
>      /// The name of the file or folder, with the extension (if any).
Alright, done

2023-12-26 00:33 UTC, Arlodotexe commented on src/IStorable.cs
> +/// The minimum representation of an item that can be stored or retrieved from storage.
Consolidating into this comment -> https://github.com/Arlodotexe/OwlCore.Storage/pull/47/files#r1436170543

2023-12-26 00:34 UTC, Arlodotexe commented on src/IMutableFolder.cs
> +    /// <returns>A disposable object which can notify of changes to the folder.</returns>
Consolidating into this comment -> https://github.com/Arlodotexe/OwlCore.Storage/pull/47/files#r1436170543

2023-12-26 11:07 UTC, d2dyno1 approved these changes

2024-01-05 03:01 UTC, merged